spring:
  datasource:
    url: jdbc:${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USER}
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
logging:
  level:
    org.springframework.security: debug
    org.springframework.web: debug
    org.springframework.messaging: debug
    sql: debug


rsa:
  private-key: ${RSA_PRIVATE_KEY}
  public-key: ${RSA_PUBLIC_KEY}