logging:
  level:
    org.springframework.security: debug
spring:
  data:
    redis:
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USER}
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:smart_tale}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

rsa:
  private-key: ${RSA_PRIVATE_KEY}
  public-key: ${RSA_PUBLIC_KEY}
server:
  port: ${PORT:8080}